### ISSUE TITLE
Missing documentation \ examples of the different capabilities

### ISSUE THREAD

**Issue by tal-abraham** [Perfecto-Quantum/Quantum-Starter-Kit#13]
We need to add a section indicating which capabilities can be added and how.
Might be done in a separate section and in more examples in the testng files, maybe commented out with short explanation beside each line.
Currently new users don't know which capabilities they can add or how.

**Comment by matthewrpm14** [comment]
Need documentation on how to add proxy settings

**Comment by sumitv-007** [comment]
Steps like below were done by Genesis for a Customer & must be explained clearly in the documentation:-

1 Cleared the cache
2 Added a class named “TestListener” under a newly created listener package (inside com.quantum) and updated the proxy host and port inside it.
3 Provided the TestListener’s relative path along with package details to the value of “wd.command.listeners” tag in application.properties file.
4 Imported a proper working JDK 1.8 to the Quantum project.
5 Updated the network settings of Eclipse Preferences

Note: You can copy your entire .m2 folder to other machines in order to skip downloading of any jar files. More info: https://stackoverflow.com/questions/31524311/copy-maven-repository-to-another-computer
