### ISSUE TITLE
Make Auto-complete feature in Eclipse work the same as IntelliJ

### ISSUE THREAD

**Issue by bkovalsky** [Perfecto-Quantum/Quantum-Starter-Kit#14]
In IntelliJ, when editing Feature files you only have to type and the options for API calls pop up automatically. But in Eclipse, you must hit Ctrl+Space to get these to pop up; request to change the Eclipse behavior to match IntelliJ.

**Comment by rkieft** [comment]
If I understand your question correctly, these settings are IntelliJ and Eclipse specific. This has nothing to do with the Quantum framework or any other framework you will be using. If you prefer to use IntelliJ you can always set up your project with IntelliJ instead of Eclipse.
Some companies prefer to let each tester/developer work with the same IDE for whatever reason. If this is the case within your company and you are stuck with using Eclipse, you can always edit your settings in Eclipse to use a auto-completion which is about the same as the one in IntelliJ.
Please see: https://stackoverflow.com/questions/6912169/eclipse-enable-autocomplete-content-assist
