### ISSUE TITLE
Scenario Outline not working and throwing error stating "required (...)+ loop did not match anything at input "

### ISSUE THREAD

**Issue by aarthi-k-lab** [Perfecto-Quantum/Quantum-Starter-Kit#53]
I am working with Quantum starter framework, Here I have to get data from JSON file so I used Scenario Outline, but still there are some issues in my gherkin file. Throwing error stating "required (...)+ loop did not match anything at input ''" near example keyword.

iachat.feature

@IA-Chat 
Feature: Basic IA chat POC 

    
@MessageBlock_TC1 
Scenario Outline: To check whether a simple message block plays 
    Given I ran the bat file for application "71 06b34ed878322d128bdcefaa44ca762e27e95838a79a4ae0141ceefb76bdbcf2" 
    Then verify whether expected message "<expectedMessage>" matches the actual message 
    
Examples: {"dataFile":"src/main/resources/data/MessageBlock.json"}
MessageBlock.json

[
  { "expectedMessage" : "Welcome , test case 1"},
  { "expectedMessage" : "1 2 3 4 5"},
  { "expectedMessage" : "The value is 10. ShockAbsorber test with variable"},
  { "expectedMessage" : "Bonjour. Merci Beacoup Monsieur"},
  { "expectedMessage" : "Thank you for calling . Dialed number is not empty"},
  { "expectedMessage" : "Thank you for calling . The CLI is between 7000 and 7010"},
  { "expectedMessage" : "Thank you for calling . This is a test call"},
  { "expectedMessage" : "Thank you for calling . After 2020."},
  { "expectedMessage" : "Thank you for calling . The current day is not sunday."}
]

**Comment by ksitwala-perfecto** [comment]
@aarthi-k-lab  - it looks like you might be using the Cucumber plugin instead of the QAF BDD plugin. Please note that Cucumber by default does not support JSON data files. QAF has customized BDD files and therefore, we need to use QAF BDD plugin in Eclipse for the syntax to not show any error. 
https://developers.perfectomobile.com/display/PD/Quantum+framework+introduction#expand-InstallanonlineversionoftheQAFBDDplugininEcliplse

In the above link the steps to install the plugin in offline mode are mentioned, in case you have a restricted network.

So the main questions are - 
Are you using Eclipse? Are you using the Cucumber gherkin plugin in eclipse?

**Comment by aarthi-k-lab** [comment]
Hi Thanks for the reply, I am currently using eclipse. I have installed QAF BDD Editor too.
But still I am facing this issue.  Please find the installed software
![image](https://user-images.githubusercontent.com/66939065/114133489-c56b9800-9923-11eb-9a67-92d235b8e00a.png)

**Comment by ksitwala-perfecto** [comment]
@aarthi-k-lab  - I am not sure which plugin is opening your feature file, Cucumber or QAF BDD. You should uninstall the Cucumber plugins in your list and then open the .feature file with the QAF BDD plugin. That might address your error. 
If I understand correctly, you are facing this issue in your IDE editor and not in the console. Correct me if I am wrong.

**Comment by aarthi-k-lab** [comment]
Thanks a lot. Working fine now

**Comment by aarthi-k-lab** [comment]
as per @ksitwala-perfecto  comment uninstalled cucumber editor plugin. It is working fine now
